### ISSUE TITLE
Vanilla JS Support

### ISSUE THREAD

**Issue by MatanYed** [ionic-team/ionic-storage#137]
Soon Ionic 4 will release, you could use Ionic 4 and Ionic Native in vanilla js.
Ionic Storage should support vanila js too, it will be great step, and no so hard as well

**Comment by mhartington** [comment]
This is really only a small lib on top of LocalForage, which is already promised based, super configurable, and has no deps on frameworks.

For now, this will be Angular only, so feel free to use LocalForage directly.

**Comment by simonhaenisch** [comment]
This is true, except that this also adds the `localforage-cordovasqlitedriver` on top of it. So I'd basically be copy-pasting half the implementation...

Storage is one of the most basic needs for any app (I guess that's why the Ionic starters all include `@ionic/storage`)... if Ionic aims to be framework-agnostic and a solution to deploy a PWA as a mobile app as well (which is one of the purposes of Capacitor I think?), then shouldn't it also be a goal to eventually provide the native APIs in a framework-agnostic way (i. e. with wrappers for frameworks like Angular and React)? Otherwise you're suggesting that if I want to build a mobile app with Ionic, I better stick with Angular because otherwise I'll have to rewrite all the native plugins myself?

Maybe someone from the community (maybe me) is willing to take care of this if it gets reopened?
