### ISSUE TITLE
Data not cleared on Android

### ISSUE THREAD

**Issue by flakerimi** [ionic-team/ionic-storage#50]
I have logout function which I try to clear all storage data and they are not cleared.

 ```
logout() {
         this.storage.clear().then((data) => {
 			console.log(data);
 		})
     	this.storage.remove('token');
    	this.storage.remove('profile');
    	this.storage.remove('login');
};   
```
In fact when I debug with chrome://inspect#device I don't see any data but they are loaded.
```
Ionic Storage driver: cordovaSQLiteDriver   SQLitePlugin.js:175 
OPEN database: _ionicstorage      SQLitePlugin.js:106 
new transaction is waiting for open operation     SQLitePlugin.js:179 
OPEN database: _ionicstorage - OK   SQLitePlugin.js:80 
DB opened: _ionicstorage         SQLitePlugin.js:80 
```

I don't see any data. In chrome web it works but not on android.
![screen shot 2016-12-05 at 22 12 34](https://cloud.githubusercontent.com/assets/871482/20902746/ce3f558e-bb38-11e6-9be9-d775e5d7dc03.png)

**Comment by tabirkeland** [comment]
Experiencing the same issue with Android.  I am actually providing my own database name in my `app.module.ts` like so:

```typescript
// Storge
import { Storage } from '@ionic/storage';

// Define Storage factory
export function storageFactory() {
    return new Storage(['sqlite', 'websql', 'indexeddb'], { name: '__my_database_name' });
}
```
I am not even seeing the database when inspecting the device application in chrome inspect.

Installed packages:

`"@ionic/storage": "1.1.7"`

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.2.0
Xcode version: Not installed
```

**Comment by mlynch** [comment]
Okay just tested this on the web with indexed db/localstorage/websql and it's working fine. I wonder if this is a bug with the sqlite engine on Android...will test more

**Comment by ivanbtrujillo** [comment]
Hi, same problem for me but only throught Google Play.

If I deploy the app to my mobile phone using ionic run android, the "remove" method works fine. On browser works well too.

If I compile the app for production: cordova build --release android (and sign etc), the remove method doesn't do anything when users press logout.

I use the storage plugin with the default configuration.

Any idea?

**Comment by silentguardian** [comment]
We are having the same issue and our code is similar to the one provided in the original report.

We also have another app which has the storage factory defined like in the second post above and that also has the same issue.

We are testing this on a Nexus 5X running 7.1.1 and the issue appears following these steps:

1) Install the app.
2) Log in with user X.
3) Log out.
4) Uninstall the app.
5) Install the app again.
6) Run the app.
7) The data stored for user X is there.

We also tried these variations which ends up with the same result:

1) Install the app.
2) Log in with user X.
3) Log out.
4) Log in with user Y.
5) Uninstall the app.
6) Install the app again.
7) Run the app.
8) The data stored for user X is there.

1) Install the app.
2) Log in with user X.
3) Log out.
4) Log in with user Y.
5) Log out.
6) Clear app data from Settings > Apps.
7) Uninstall the app.
8) Install the app again.
9) Run the app.
10) The data stored for user X is there.

We have another testing device, a Sony LT22i running 4.1.2 and this has never happened with that device.

We use the Crosswalk plugin for Android < 5.0, so that might be one reason why it was okay on this second device.

We believe that this is a serious issue as many apps rely on this storage for authentication.

I would be happy to provide additional information if needed.

**Comment by sahildaga95** [comment]
+1 ,
@ionic/storage": "2.0.1"
Device: Samsung J2
Android Version- 6.0.1

**Comment by itsvick** [comment]
Same issue here too. We able to replicate above issue in our app too. expecting solution for this.

**Comment by Malkiat-Singh** [comment]
yeah Same issue here as well

**Comment by itsvick** [comment]
@Malkiat-Singh try to add this line <preference name="BackupWebStorage" value="none" /> in config.xml

**Comment by Malkiat-Singh** [comment]
@itsvick  which line please

**Comment by vivek-kasture** [comment]
@Malkiat-Singh sorry, I missed to add <preference name="BackupWebStorage" value="none" />

**Comment by vivek-kasture** [comment]
preference name="BackupWebStorage" value="none"

**Comment by xpagliosa** [comment]
Include android:allowBackup="false" android:fullBackupContent="false"  in <application> section of  AndroidManifest.xml

**Comment by xpagliosa** [comment]
@KrunchMuffin In application section

**Comment by KrunchMuffin** [comment]
I got it to clear now. THis is what I did. 
in `config.xml'
```
    <preference name="InAppBrowserStorageEnabled" value="false" />
    <platform name="android">
        <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:allowBackup="false" />
            <application android:fullBackupContent="false" />
        </edit-config>
   ...
   </platform>
```
and I also implemented the `clear()` method from ionic even tho I was removing each item already.
https://ionicframework.com/docs/storage/#clear
